### PR TITLE
use discName when renaming output with handBrakeCLI

### PR DESCRIPTION
**Pull request by eleith**
since makemkvcon can usually get the title of the movie through the name of the disc, grab this early in the process. 

later on, handbrake allows you to rename the output file to whatever you want, pass in the discName here and you will end up with `MOVIE NAME.mkv` instead of `title00.mkv`. 

i also handle the cases where the discName isn't found, or the user chooses to rip multiple titles out of the disc.

lastly, after ripping, update the video library to pick up the new movie.

### CODE REVIEW

**Comment by reverendj1** [comment]
This looks great, thanks! One small thing though. Will you please add library updating as a per profile option? Since we don't really do any advanced renaming, people will (most likely) have to rename files when there are multiple titles on a disc, like for TV shows, behind the scenes features, or when a movie has multiple language *videos* (where they translate street signs and such). Because of this and other reasons, I always dump my movies to a temp folder to make sure everything was gravy before putting them into my library. Thanks for the help. I'll try to run some tests on this soon and get it pulled once you do that.

**Comment by eleith** [comment]
sure thing @reverendj1  

the request makes sense. i think if you are putting the output into a temp folder, the update command would be harmless, but making it a preference would give more fine grained control to the user.

i wish preferences and the 10 profiles were easier to deal with...

any ideas on how to solve for tv shows, features, multiple language videos that you describe? or is manual  the best way to go about it?

anyhow, i've made the changes you requested. i haven't tested it out yet though. fyi.

**Comment by reverendj1** [comment]
Thanks for the update. Yeah, having the 10 hardcoded profiles is pretty annoying and hacky, but I couldn't figure out a way to create settings dynamically, and I couldn't find any examples of anyone else doing it in plugins either. I agree that updating automatically would be mostly harmless, but there *may* be other cases where it is undesirable.

We could create a renaming scheme for the TV shows, that would be editable for user preference. However, that and renaming individual titles from a movie will always require user input, or make a lot of assumptions, which will cause more issues than they would solve, I think. In the case of a TV show, to have any sort of renaming, we would need to know the season, and first episode on the disc. But, then for it to actually work, you have to assume that the titles are in order. In my experience, this is far from guaranteed. There's also no way to know what titles in a movie are (if they are not given by your new method here) without manually watching the videos, and naming them. The only thing I could think of that would really help solve these issues is to have some sort of step after the videos are ripped, where you could preview them, and then name them (or possibly delete them, so you don't waste time encoding crap titles), however, that really doesn't provide any benefit over setting separate ripping and encoding profiles and editing the filenames in between.

**Comment by eleith** [comment]
thanks for the explanation.

for the preferences, a helper script could generate the XML file, but making that script likely takes more time than just copying it ten time =]

let me know about any updates or bugs you find in this branch. happy to clean it up.

**Comment by reverendj1** [comment]
Sorry, I forgot about this. Merged.

**Pull request merged**
